name: "Track TODOs"
on:
  push:
    branches:
      - main
jobs:
  track-todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Track TODOs
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "tests=testing"
